# Generated by Django 3.2.4 on 2021-11-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel_invest_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_address',
        ),
    ]
