# Generated by Django 3.2.4 on 2021-11-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_invest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmpayment',
            name='package',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
