# Generated by Django 3.2.4 on 2021-10-31 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_invest_app', '0002_auto_20211021_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=250)),
                ('package_price', models.IntegerField()),
                ('package_description', models.TextField(blank=True, null=True)),
                ('investors', models.ManyToManyField(related_name='investors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
