# Generated by Django 3.2.4 on 2021-11-13 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intel_invest_app', '0003_cryptocurrency_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.CharField(blank=True, max_length=250, null=True)),
                ('ethereum', models.CharField(blank=True, max_length=250, null=True)),
                ('litecoin', models.CharField(blank=True, max_length=250, null=True)),
                ('bnb', models.CharField(blank=True, max_length=250, null=True)),
                ('busd', models.CharField(blank=True, max_length=250, null=True)),
                ('usdt', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
