# Generated by Django 3.2.4 on 2021-11-01 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_invest_app', '0003_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='investors',
            field=models.ManyToManyField(blank=True, related_name='investors', to=settings.AUTH_USER_MODEL),
        ),
    ]
