# Generated by Django 3.2.4 on 2021-11-15 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intel_invest_app', '0004_userwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(upload_to='screenshot/user-payment/'),
        ),
        migrations.CreateModel(
            name='ConfirmPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever_email', models.EmailField(max_length=250)),
                ('reciever_account', models.CharField(max_length=350)),
                ('body', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.ImageField(upload_to='screenshot/confirm-payment/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
